# Generated by Django 5.0.3 on 2024-09-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='id',
            field=models.CharField(default='GivemeId', max_length=100),
        ),
    ]
