# Generated by Django 5.0.3 on 2024-09-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_question_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='id',
            new_name='question_id',
        ),
    ]
