# Generated by Django 5.0.3 on 2024-09-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_id_question_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='keyed',
            field=models.CharField(max_length=10),
        ),
    ]
